name: models
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.3.2

dev_dependencies:
  build_runner: ^2.15.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^5.3.2

flutter:
