// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/cross_reference.dart';
import 'src/meditation_playlist.dart';
import 'src/metadata.dart';
import 'src/playlist_item.dart';
import 'src/verse.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3546499605548449245),
    name: 'CrossReference',
    lastPropertyId: const obx_int.IdUid(4, 3997700867677226490),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1775954466397370093),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1710348846469322605),
        name: 'sourceVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 7807475108485719313),
        relationField: 'sourceVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6553568043877273804),
        name: 'relatedVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 5757325043275853582),
        relationField: 'relatedVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3997700867677226490),
        name: 'weight',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(6, 8379795609271225814),
    name: 'PlaylistItem',
    lastPropertyId: const obx_int.IdUid(4, 2504596250486258632),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 474806609586836313),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1749196803060034374),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 1707994132779685612),
        relationField: 'playlist',
        relationTarget: 'MeditationPlaylist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2974613144490265516),
        name: 'verseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 6399301089202165551),
        relationField: 'verse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2504596250486258632),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 2214344021986212333),
    name: 'MeditationPlaylist',
    lastPropertyId: const obx_int.IdUid(3, 6980963724074942879),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7464846729035417568),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8922881965815583852),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6980963724074942879),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 790814190769568083),
        name: 'items',
        targetId: const obx_int.IdUid(6, 8379795609271225814),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 3890027473025477599),
    name: 'Metadata',
    lastPropertyId: const obx_int.IdUid(11, 3782261739662360129),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1011731178386730065),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1963016350382378077),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1582098096356129446),
        name: 'shortname',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 5725041447701703667),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6115636324748559350),
        name: 'module',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6219379861141269716),
        name: 'year',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6756359992663534256),
        name: 'publisher',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4293048652992687769),
        name: 'owner',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 158432357048145000),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7120149939657702095),
        name: 'lang',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7900534065784778365),
        name: 'langShort',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3782261739662360129),
        name: 'copyrightStatement',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 8489944971351774024),
    name: 'Verse',
    lastPropertyId: const obx_int.IdUid(8, 3464414837333731609),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2964034781998262364),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8821158339924011953),
        name: 'reference',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 6785230692318440910),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6270851429001924652),
        name: 'book',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(13, 5330081434616714312),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1904923254652677788),
        name: 'chapter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4289107915045265973),
        name: 'verse',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3928922443664453215),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7212030081692829614),
        name: 'translation',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3464414837333731609),
        name: 'metadataId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 8023906606349551837),
        relationField: 'metadata',
        relationTarget: 'Metadata',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'references',
        srcEntity: 'CrossReference',
        srcField: 'sourceVerse',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(9, 8489944971351774024),
    lastIndexId: const obx_int.IdUid(14, 8023906606349551837),
    lastRelationId: const obx_int.IdUid(2, 790814190769568083),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      7791345875852312257,
      1021189109591873552,
      91889918951979563,
      3160260449548396220,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      7129128353696499471,
      8889419185661275642,
      7511637962366237687,
      6466569955670898907,
      4106185461765933107,
      4327969715326238161,
      3789691750206635354,
      8767523679426092246,
      4886180285984584922,
      8373675238446117924,
      2581059691119494902,
      7628743983727105264,
      2430605219461517686,
      7826691864367915196,
      2864625648471129206,
      2095267925952215025,
      6841577646520005701,
      6299177473788460423,
    ],
    retiredRelationUids: const [2872771344200630570],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CrossReference: obx_int.EntityDefinition<CrossReference>(
      model: _entities[0],
      toOneRelations: (CrossReference object) => [
        object.sourceVerse,
        object.relatedVerse,
      ],
      toManyRelations: (CrossReference object) => {},
      getId: (CrossReference object) => object.id,
      setId: (CrossReference object, int id) {
        object.id = id;
      },
      objectToFB: (CrossReference object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sourceVerse.targetId);
        fbb.addInt64(2, object.relatedVerse.targetId);
        fbb.addInt64(3, object.weight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final weightParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = CrossReference(id: idParam, weight: weightParam);
        object.sourceVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sourceVerse.attach(store);
        object.relatedVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.relatedVerse.attach(store);
        return object;
      },
    ),
    PlaylistItem: obx_int.EntityDefinition<PlaylistItem>(
      model: _entities[1],
      toOneRelations: (PlaylistItem object) => [object.playlist, object.verse],
      toManyRelations: (PlaylistItem object) => {},
      getId: (PlaylistItem object) => object.id,
      setId: (PlaylistItem object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistItem object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.playlist.targetId);
        fbb.addInt64(2, object.verse.targetId);
        fbb.addInt64(3, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sortOrderParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = PlaylistItem(id: idParam, sortOrder: sortOrderParam);
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.playlist.attach(store);
        object.verse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.verse.attach(store);
        return object;
      },
    ),
    MeditationPlaylist: obx_int.EntityDefinition<MeditationPlaylist>(
      model: _entities[2],
      toOneRelations: (MeditationPlaylist object) => [],
      toManyRelations: (MeditationPlaylist object) => {
        obx_int.RelInfo<MeditationPlaylist>.toMany(2, object.id): object.items,
      },
      getId: (MeditationPlaylist object) => object.id,
      setId: (MeditationPlaylist object, int id) {
        object.id = id;
      },
      objectToFB: (MeditationPlaylist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = MeditationPlaylist(
          id: idParam,
          name: nameParam,
          createdAt: createdAtParam,
        );
        obx_int.InternalToManyAccess.setRelInfo<MeditationPlaylist>(
          object.items,
          store,
          obx_int.RelInfo<MeditationPlaylist>.toMany(2, object.id),
        );
        return object;
      },
    ),
    Metadata: obx_int.EntityDefinition<Metadata>(
      model: _entities[3],
      toOneRelations: (Metadata object) => [],
      toManyRelations: (Metadata object) => {},
      getId: (Metadata object) => object.id,
      setId: (Metadata object, int id) {
        object.id = id;
      },
      objectToFB: (Metadata object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final shortnameOffset = fbb.writeString(object.shortname);
        final moduleOffset = fbb.writeString(object.module);
        final yearOffset = fbb.writeString(object.year);
        final publisherOffset = object.publisher == null
            ? null
            : fbb.writeString(object.publisher!);
        final ownerOffset = object.owner == null
            ? null
            : fbb.writeString(object.owner!);
        final descriptionOffset = fbb.writeString(object.description);
        final langOffset = fbb.writeString(object.lang);
        final langShortOffset = fbb.writeString(object.langShort);
        final copyrightStatementOffset = fbb.writeString(
          object.copyrightStatement,
        );
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, shortnameOffset);
        fbb.addOffset(3, moduleOffset);
        fbb.addOffset(4, yearOffset);
        fbb.addOffset(5, publisherOffset);
        fbb.addOffset(6, ownerOffset);
        fbb.addOffset(7, descriptionOffset);
        fbb.addOffset(8, langOffset);
        fbb.addOffset(9, langShortOffset);
        fbb.addOffset(10, copyrightStatementOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final shortnameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final moduleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final yearParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final publisherParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final ownerParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final langParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final langShortParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final copyrightStatementParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final object = Metadata(
          id: idParam,
          name: nameParam,
          shortname: shortnameParam,
          module: moduleParam,
          year: yearParam,
          publisher: publisherParam,
          owner: ownerParam,
          description: descriptionParam,
          lang: langParam,
          langShort: langShortParam,
          copyrightStatement: copyrightStatementParam,
        );

        return object;
      },
    ),
    Verse: obx_int.EntityDefinition<Verse>(
      model: _entities[4],
      toOneRelations: (Verse object) => [object.metadata],
      toManyRelations: (Verse object) => {
        obx_int.RelInfo<CrossReference>.toOneBacklink(
          2,
          object.id,
          (CrossReference srcObject) => srcObject.sourceVerse,
        ): object.references,
      },
      getId: (Verse object) => object.id,
      setId: (Verse object, int id) {
        object.id = id;
      },
      objectToFB: (Verse object, fb.Builder fbb) {
        final referenceOffset = fbb.writeString(object.reference);
        final textOffset = fbb.writeString(object.text);
        final translationOffset = fbb.writeString(object.translation);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, referenceOffset);
        fbb.addInt64(2, object.book);
        fbb.addInt64(3, object.chapter);
        fbb.addInt64(4, object.verse);
        fbb.addOffset(5, textOffset);
        fbb.addOffset(6, translationOffset);
        fbb.addInt64(7, object.metadata.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final referenceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bookParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final chapterParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final verseParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final translationParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final object = Verse(
          id: idParam,
          reference: referenceParam,
          book: bookParam,
          chapter: chapterParam,
          verse: verseParam,
          text: textParam,
          translation: translationParam,
        );
        object.metadata.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        object.metadata.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<Verse>(
          object.references,
          store,
          obx_int.RelInfo<CrossReference>.toOneBacklink(
            2,
            object.id,
            (CrossReference srcObject) => srcObject.sourceVerse,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CrossReference] entity fields to define ObjectBox queries.
class CrossReference_ {
  /// See [CrossReference.id].
  static final id = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[0],
  );

  /// See [CrossReference.sourceVerse].
  static final sourceVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[1],
  );

  /// See [CrossReference.relatedVerse].
  static final relatedVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[2],
  );

  /// See [CrossReference.weight].
  static final weight = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[3],
  );
}

/// [PlaylistItem] entity fields to define ObjectBox queries.
class PlaylistItem_ {
  /// See [PlaylistItem.id].
  static final id = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[1].properties[0],
  );

  /// See [PlaylistItem.playlist].
  static final playlist =
      obx.QueryRelationToOne<PlaylistItem, MeditationPlaylist>(
        _entities[1].properties[1],
      );

  /// See [PlaylistItem.verse].
  static final verse = obx.QueryRelationToOne<PlaylistItem, Verse>(
    _entities[1].properties[2],
  );

  /// See [PlaylistItem.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[1].properties[3],
  );
}

/// [MeditationPlaylist] entity fields to define ObjectBox queries.
class MeditationPlaylist_ {
  /// See [MeditationPlaylist.id].
  static final id = obx.QueryIntegerProperty<MeditationPlaylist>(
    _entities[2].properties[0],
  );

  /// See [MeditationPlaylist.name].
  static final name = obx.QueryStringProperty<MeditationPlaylist>(
    _entities[2].properties[1],
  );

  /// See [MeditationPlaylist.createdAt].
  static final createdAt = obx.QueryDateProperty<MeditationPlaylist>(
    _entities[2].properties[2],
  );

  /// see [MeditationPlaylist.items]
  static final items =
      obx.QueryRelationToMany<MeditationPlaylist, PlaylistItem>(
        _entities[2].relations[0],
      );
}

/// [Metadata] entity fields to define ObjectBox queries.
class Metadata_ {
  /// See [Metadata.id].
  static final id = obx.QueryIntegerProperty<Metadata>(
    _entities[3].properties[0],
  );

  /// See [Metadata.name].
  static final name = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[1],
  );

  /// See [Metadata.shortname].
  static final shortname = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[2],
  );

  /// See [Metadata.module].
  static final module = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[3],
  );

  /// See [Metadata.year].
  static final year = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[4],
  );

  /// See [Metadata.publisher].
  static final publisher = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[5],
  );

  /// See [Metadata.owner].
  static final owner = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[6],
  );

  /// See [Metadata.description].
  static final description = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[7],
  );

  /// See [Metadata.lang].
  static final lang = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[8],
  );

  /// See [Metadata.langShort].
  static final langShort = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[9],
  );

  /// See [Metadata.copyrightStatement].
  static final copyrightStatement = obx.QueryStringProperty<Metadata>(
    _entities[3].properties[10],
  );
}

/// [Verse] entity fields to define ObjectBox queries.
class Verse_ {
  /// See [Verse.id].
  static final id = obx.QueryIntegerProperty<Verse>(_entities[4].properties[0]);

  /// See [Verse.reference].
  static final reference = obx.QueryStringProperty<Verse>(
    _entities[4].properties[1],
  );

  /// See [Verse.book].
  static final book = obx.QueryIntegerProperty<Verse>(
    _entities[4].properties[2],
  );

  /// See [Verse.chapter].
  static final chapter = obx.QueryIntegerProperty<Verse>(
    _entities[4].properties[3],
  );

  /// See [Verse.verse].
  static final verse = obx.QueryIntegerProperty<Verse>(
    _entities[4].properties[4],
  );

  /// See [Verse.text].
  static final text = obx.QueryStringProperty<Verse>(
    _entities[4].properties[5],
  );

  /// See [Verse.translation].
  static final translation = obx.QueryStringProperty<Verse>(
    _entities[4].properties[6],
  );

  /// See [Verse.metadata].
  static final metadata = obx.QueryRelationToOne<Verse, Metadata>(
    _entities[4].properties[7],
  );

  /// see [Verse.references]
  static final references = obx.QueryBacklinkToMany<CrossReference, Verse>(
    CrossReference_.sourceVerse,
  );
}
