// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'models/cross_reference.dart';
import 'models/verse.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3191769014581596681),
    name: 'CrossReference',
    lastPropertyId: const obx_int.IdUid(4, 1476907495242914587),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 458385319270705752),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8475042921773591458),
        name: 'sourceVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 1112436064440317633),
        relationField: 'sourceVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2351733655352294483),
        name: 'relatedVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1860157126774660615),
        relationField: 'relatedVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1476907495242914587),
        name: 'weight',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 580312705760554689),
    name: 'Verse',
    lastPropertyId: const obx_int.IdUid(7, 2002649550900099643),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4186533040986951770),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4130720537340740571),
        name: 'reference',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 7868431798941484870),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 107204383206556302),
        name: 'book',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(4, 357794926886396049),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1312273018070645975),
        name: 'chapter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8725863063810354179),
        name: 'verse',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7353765188104531838),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2002649550900099643),
        name: 'translation',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'crossReferences',
        srcEntity: 'CrossReference',
        srcField: 'sourceVerse',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 580312705760554689),
    lastIndexId: const obx_int.IdUid(4, 357794926886396049),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CrossReference: obx_int.EntityDefinition<CrossReference>(
      model: _entities[0],
      toOneRelations: (CrossReference object) => [
        object.sourceVerse,
        object.relatedVerse,
      ],
      toManyRelations: (CrossReference object) => {},
      getId: (CrossReference object) => object.id,
      setId: (CrossReference object, int id) {
        object.id = id;
      },
      objectToFB: (CrossReference object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sourceVerse.targetId);
        fbb.addInt64(2, object.relatedVerse.targetId);
        fbb.addInt64(3, object.weight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CrossReference()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..weight = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          );
        object.sourceVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sourceVerse.attach(store);
        object.relatedVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.relatedVerse.attach(store);
        return object;
      },
    ),
    Verse: obx_int.EntityDefinition<Verse>(
      model: _entities[1],
      toOneRelations: (Verse object) => [],
      toManyRelations: (Verse object) => {
        obx_int.RelInfo<CrossReference>.toOneBacklink(
          2,
          object.id,
          (CrossReference srcObject) => srcObject.sourceVerse,
        ): object.crossReferences,
      },
      getId: (Verse object) => object.id,
      setId: (Verse object, int id) {
        object.id = id;
      },
      objectToFB: (Verse object, fb.Builder fbb) {
        final referenceOffset = fbb.writeString(object.reference);
        final textOffset = fbb.writeString(object.text);
        final translationOffset = fbb.writeString(object.translation);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, referenceOffset);
        fbb.addInt64(2, object.book);
        fbb.addInt64(3, object.chapter);
        fbb.addInt64(4, object.verse);
        fbb.addOffset(5, textOffset);
        fbb.addOffset(6, translationOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Verse()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..reference = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..book = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..chapter = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..verse = const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..translation = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '');
        obx_int.InternalToManyAccess.setRelInfo<Verse>(
          object.crossReferences,
          store,
          obx_int.RelInfo<CrossReference>.toOneBacklink(
            2,
            object.id,
            (CrossReference srcObject) => srcObject.sourceVerse,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CrossReference] entity fields to define ObjectBox queries.
class CrossReference_ {
  /// See [CrossReference.id].
  static final id = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[0],
  );

  /// See [CrossReference.sourceVerse].
  static final sourceVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[1],
  );

  /// See [CrossReference.relatedVerse].
  static final relatedVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[2],
  );

  /// See [CrossReference.weight].
  static final weight = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[3],
  );
}

/// [Verse] entity fields to define ObjectBox queries.
class Verse_ {
  /// See [Verse.id].
  static final id = obx.QueryIntegerProperty<Verse>(_entities[1].properties[0]);

  /// See [Verse.reference].
  static final reference = obx.QueryStringProperty<Verse>(
    _entities[1].properties[1],
  );

  /// See [Verse.book].
  static final book = obx.QueryIntegerProperty<Verse>(
    _entities[1].properties[2],
  );

  /// See [Verse.chapter].
  static final chapter = obx.QueryIntegerProperty<Verse>(
    _entities[1].properties[3],
  );

  /// See [Verse.verse].
  static final verse = obx.QueryIntegerProperty<Verse>(
    _entities[1].properties[4],
  );

  /// See [Verse.text].
  static final text = obx.QueryStringProperty<Verse>(
    _entities[1].properties[5],
  );

  /// See [Verse.translation].
  static final translation = obx.QueryStringProperty<Verse>(
    _entities[1].properties[6],
  );

  /// see [Verse.crossReferences]
  static final crossReferences = obx.QueryBacklinkToMany<CrossReference, Verse>(
    CrossReference_.sourceVerse,
  );
}
