// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../_shared/models/cross_reference.dart';
import '../../_shared/models/verse.dart';
import '../../features/playlist/model/meditation_playlist.dart';
import '../../features/playlist/model/playlist_item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 354332807247982098),
    name: 'CrossReference',
    lastPropertyId: const obx_int.IdUid(4, 2853565290544557554),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4152418166151100086),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5682639337955044998),
        name: 'sourceVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3666657424300082813),
        relationField: 'sourceVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6404681503270272250),
        name: 'relatedVerseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 5585491963266546926),
        relationField: 'relatedVerse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2853565290544557554),
        name: 'weight',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4073387215371943270),
    name: 'MeditationPlaylist',
    lastPropertyId: const obx_int.IdUid(3, 9214361447567419047),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6098796731707463439),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8974436372291287467),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9214361447567419047),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 7341903444045702093),
        name: 'items',
        targetId: const obx_int.IdUid(3, 8505276387343362100),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8505276387343362100),
    name: 'PlaylistItem',
    lastPropertyId: const obx_int.IdUid(4, 4548367879856344595),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2095878827906661709),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8864342289156978138),
        name: 'playlistId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 2484560194846658596),
        relationField: 'playlist',
        relationTarget: 'MeditationPlaylist',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3490482905732988770),
        name: 'verseId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 5558133557672060029),
        relationField: 'verse',
        relationTarget: 'Verse',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4548367879856344595),
        name: 'sortOrder',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 2021634148547483745),
    name: 'Verse',
    lastPropertyId: const obx_int.IdUid(7, 5296374202771655773),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5823241831972482069),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 127338482526994345),
        name: 'reference',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 309598289880035587),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5958914277455406337),
        name: 'book',
        type: 6,
        flags: 8,
        indexId: const obx_int.IdUid(6, 469586121239963366),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4226722228697544423),
        name: 'chapter',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7653784074115528295),
        name: 'verse',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 465532983368182692),
        name: 'text',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 5510217929477166689),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5296374202771655773),
        name: 'translation',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'crossReferences',
        srcEntity: 'CrossReference',
        srcField: 'sourceVerse',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 2021634148547483745),
    lastIndexId: const obx_int.IdUid(7, 5510217929477166689),
    lastRelationId: const obx_int.IdUid(2, 6584114347613462968),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [6584114347613462968],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CrossReference: obx_int.EntityDefinition<CrossReference>(
      model: _entities[0],
      toOneRelations: (CrossReference object) => [
        object.sourceVerse,
        object.relatedVerse,
      ],
      toManyRelations: (CrossReference object) => {},
      getId: (CrossReference object) => object.id,
      setId: (CrossReference object, int id) {
        object.id = id;
      },
      objectToFB: (CrossReference object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.sourceVerse.targetId);
        fbb.addInt64(2, object.relatedVerse.targetId);
        fbb.addInt64(3, object.weight);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CrossReference()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..weight = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          );
        object.sourceVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.sourceVerse.attach(store);
        object.relatedVerse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.relatedVerse.attach(store);
        return object;
      },
    ),
    MeditationPlaylist: obx_int.EntityDefinition<MeditationPlaylist>(
      model: _entities[1],
      toOneRelations: (MeditationPlaylist object) => [],
      toManyRelations: (MeditationPlaylist object) => {
        obx_int.RelInfo<MeditationPlaylist>.toMany(1, object.id): object.items,
      },
      getId: (MeditationPlaylist object) => object.id,
      setId: (MeditationPlaylist object, int id) {
        object.id = id;
      },
      objectToFB: (MeditationPlaylist object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = MeditationPlaylist()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          );
        obx_int.InternalToManyAccess.setRelInfo<MeditationPlaylist>(
          object.items,
          store,
          obx_int.RelInfo<MeditationPlaylist>.toMany(1, object.id),
        );
        return object;
      },
    ),
    PlaylistItem: obx_int.EntityDefinition<PlaylistItem>(
      model: _entities[2],
      toOneRelations: (PlaylistItem object) => [object.playlist, object.verse],
      toManyRelations: (PlaylistItem object) => {},
      getId: (PlaylistItem object) => object.id,
      setId: (PlaylistItem object, int id) {
        object.id = id;
      },
      objectToFB: (PlaylistItem object, fb.Builder fbb) {
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.playlist.targetId);
        fbb.addInt64(2, object.verse.targetId);
        fbb.addInt64(3, object.sortOrder);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = PlaylistItem()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..sortOrder = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          );
        object.playlist.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        object.playlist.attach(store);
        object.verse.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        object.verse.attach(store);
        return object;
      },
    ),
    Verse: obx_int.EntityDefinition<Verse>(
      model: _entities[3],
      toOneRelations: (Verse object) => [],
      toManyRelations: (Verse object) => {
        obx_int.RelInfo<CrossReference>.toOneBacklink(
          2,
          object.id,
          (CrossReference srcObject) => srcObject.sourceVerse,
        ): object.crossReferences,
      },
      getId: (Verse object) => object.id,
      setId: (Verse object, int id) {
        object.id = id;
      },
      objectToFB: (Verse object, fb.Builder fbb) {
        final referenceOffset = fbb.writeString(object.reference);
        final textOffset = fbb.writeString(object.text);
        final translationOffset = fbb.writeString(object.translation);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, referenceOffset);
        fbb.addInt64(2, object.book);
        fbb.addInt64(3, object.chapter);
        fbb.addInt64(4, object.verse);
        fbb.addOffset(5, textOffset);
        fbb.addOffset(6, translationOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Verse()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..reference = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..book = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..chapter = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..verse = const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
          ..text = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..translation = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '');
        obx_int.InternalToManyAccess.setRelInfo<Verse>(
          object.crossReferences,
          store,
          obx_int.RelInfo<CrossReference>.toOneBacklink(
            2,
            object.id,
            (CrossReference srcObject) => srcObject.sourceVerse,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CrossReference] entity fields to define ObjectBox queries.
class CrossReference_ {
  /// See [CrossReference.id].
  static final id = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[0],
  );

  /// See [CrossReference.sourceVerse].
  static final sourceVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[1],
  );

  /// See [CrossReference.relatedVerse].
  static final relatedVerse = obx.QueryRelationToOne<CrossReference, Verse>(
    _entities[0].properties[2],
  );

  /// See [CrossReference.weight].
  static final weight = obx.QueryIntegerProperty<CrossReference>(
    _entities[0].properties[3],
  );
}

/// [MeditationPlaylist] entity fields to define ObjectBox queries.
class MeditationPlaylist_ {
  /// See [MeditationPlaylist.id].
  static final id = obx.QueryIntegerProperty<MeditationPlaylist>(
    _entities[1].properties[0],
  );

  /// See [MeditationPlaylist.name].
  static final name = obx.QueryStringProperty<MeditationPlaylist>(
    _entities[1].properties[1],
  );

  /// See [MeditationPlaylist.createdAt].
  static final createdAt = obx.QueryDateProperty<MeditationPlaylist>(
    _entities[1].properties[2],
  );

  /// see [MeditationPlaylist.items]
  static final items =
      obx.QueryRelationToMany<MeditationPlaylist, PlaylistItem>(
        _entities[1].relations[0],
      );
}

/// [PlaylistItem] entity fields to define ObjectBox queries.
class PlaylistItem_ {
  /// See [PlaylistItem.id].
  static final id = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[2].properties[0],
  );

  /// See [PlaylistItem.playlist].
  static final playlist =
      obx.QueryRelationToOne<PlaylistItem, MeditationPlaylist>(
        _entities[2].properties[1],
      );

  /// See [PlaylistItem.verse].
  static final verse = obx.QueryRelationToOne<PlaylistItem, Verse>(
    _entities[2].properties[2],
  );

  /// See [PlaylistItem.sortOrder].
  static final sortOrder = obx.QueryIntegerProperty<PlaylistItem>(
    _entities[2].properties[3],
  );
}

/// [Verse] entity fields to define ObjectBox queries.
class Verse_ {
  /// See [Verse.id].
  static final id = obx.QueryIntegerProperty<Verse>(_entities[3].properties[0]);

  /// See [Verse.reference].
  static final reference = obx.QueryStringProperty<Verse>(
    _entities[3].properties[1],
  );

  /// See [Verse.book].
  static final book = obx.QueryIntegerProperty<Verse>(
    _entities[3].properties[2],
  );

  /// See [Verse.chapter].
  static final chapter = obx.QueryIntegerProperty<Verse>(
    _entities[3].properties[3],
  );

  /// See [Verse.verse].
  static final verse = obx.QueryIntegerProperty<Verse>(
    _entities[3].properties[4],
  );

  /// See [Verse.text].
  static final text = obx.QueryStringProperty<Verse>(
    _entities[3].properties[5],
  );

  /// See [Verse.translation].
  static final translation = obx.QueryStringProperty<Verse>(
    _entities[3].properties[6],
  );

  /// see [Verse.crossReferences]
  static final crossReferences = obx.QueryBacklinkToMany<CrossReference, Verse>(
    CrossReference_.sourceVerse,
  );
}
